---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: atomix
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 42 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/che/nerd-fonts/repo/fedora-%OS_VERSION%/che-nerd-fonts-fedora-%OS_VERSION%.repo
    install:
      - micro
      - starship
      - distrobox
      - gnome-tweaks
      - gnome-shell-extension-appindicator
      - gnome-shell-extension-blur-my-shell
      - gnome-shell-extension-gpaste
      - gnome-shell-extension-just-perfection
      - gnome-shell-extension-gsconnect
      - input-leap
      - nerd-fonts
      - openssh-askpass
      - pulseaudio-utils
      - python3-pip
      - zsh
      - android-tools
      - android-file-transfer
      - libvirt
      - bootc
#      - podman-bootc
      - podman-compose
      - qemu
      - qemu-char-spice
      - qemu-device-display-virtio-gpu
      - qemu-device-display-virtio-vga
      - qemu-device-usb-redirect
      - qemu-img
      - qemu-system-x86-core
      - qemu-user-binfmt
      - qemu-user-static
      - virt-manager
      - virt-v2v
      - virt-viewer
      - ydotool
    remove:
      # example: removing firefox (in favor of the flatpak)
      # "firefox" is the main package, "firefox-langpacks" is a dependency
      - firefox
      - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
          - org.gnome.Loupe
      - scope: user # Also add Flathub user repo, but no user packages
        install: # system flatpaks we want all users to have and not remove
          - app.zen_browser.zen
          - dev.zed.Zed
          - app.devsuite.Ptyxis
          - com.github.tchx84.Flatseal
          - io.bassi.Amberol

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
